[package]
name = "wasi-test"
version = "0.0.0"
authors = ["Casper Beyer <caspervonb@pm.me>"]
edition = "2018"

[build-dependencies]
serde = "1.0"
serde_json = "1.0"

[dependencies]
wasi = "0.10.0+wasi-snapshot-preview1"

[profile.release]
lto = true
