name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.43.0
        targets: wasm32-wasi

    - name: Build
      run: cargo build --target=wasm32-wasi
