name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Clang
      run: |
        curl -L https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-11/wasi-sdk-11.0-linux.tar.gz | tar -xzf -
        mv wasi-sdk-11.0 /opt/wasi-sdk
        echo "::add-path::/opt/wasi-sdk/bin"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.43.0
        targets: wasm32-wasi

    - name: Build
      run: ./build.py
